"""
RetailFlow Pipeline — CSV to PostgreSQL Loader
===============================================

Reads the raw CSV files generated by generate_fake_data.py and loads them
into the PostgreSQL `raw` schema.

The script:
    - Connects to PostgreSQL using environment variables
    - Creates the `raw` schema if it does not exist
    - Truncates existing data in each raw table (idempotent)
    - Streams CSV content into the corresponding table

Usage:
    python scripts/load_to_postgres.py

Environment variables (from .env):
    POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
"""

import logging
import os
import sys
from datetime import datetime
from typing import Dict, List, Tuple

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

logger = logging.getLogger(__name__)

# Mapping of CSV file → PostgreSQL table name
CSV_TABLE_MAP: List[Tuple[str, str]] = [
    ("customers.csv", "raw.customers"),
    ("products.csv", "raw.products"),
    ("orders.csv", "raw.orders"),
]

# Column type overrides to ensure correct data types when loading from CSV
DTYPE_MAP: Dict[str, object] = {
    "customer_id": "string",
    "product_id": "string",
    "order_id": "string",
    "first_name": "string",
    "last_name": "string",
    "email": "string",
    "country": "string",
    "city": "string",
    "signup_date": "string",
    "gender": "string",
    "name": "string",
    "category": "string",
    "supplier_country": "string",
    "status": "string",
}


def get_engine() -> Engine:
    """Create a SQLAlchemy engine from environment variables.

    Returns:
        A SQLAlchemy Engine connected to the PostgreSQL database.

    Raises:
        ValueError: If required environment variables are missing.
    """
    host = os.getenv("POSTGRES_HOST", "localhost")
    port = os.getenv("POSTGRES_PORT", "5432")
    database = os.getenv("POSTGRES_DB", "retailflow")
    user = os.getenv("POSTGRES_USER", "retailflow_user")
    password = os.getenv("POSTGRES_PASSWORD", "retailflow_pass")

    # WHY: SQLAlchemy connection string format for psycopg2.
    connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
    engine = create_engine(connection_string, echo=False)
    logger.info("Connected to PostgreSQL at %s:%s/%s", host, port, database)
    return engine


def ensure_raw_schema(engine: Engine) -> None:
    """Create the `raw` schema in PostgreSQL if it does not exist.

    Args:
        engine: SQLAlchemy Engine instance.
    """
    with engine.connect() as conn:
        conn.exec_driver_sql("CREATE SCHEMA IF NOT EXISTS raw;")
        conn.commit()
    logger.info("Ensured raw schema exists.")


def truncate_table(engine: Engine, table_name: str) -> None:
    """Remove all rows from a table (idempotent load).

    Args:
        engine: SQLAlchemy Engine instance.
        table_name: Fully qualified table name (e.g., 'raw.customers').
    """
    with engine.connect() as conn:
        # WHY: Use TRUNCATE instead of DELETE for faster cleanup on large tables.
        conn.exec_driver_sql(f"TRUNCATE TABLE {table_name} RESTART IDENTITY CASCADE;")
        conn.commit()
    logger.info("Truncated table: %s", table_name)


def load_csv_to_table(engine: Engine, csv_filename: str, table_name: str) -> int:
    """Read a CSV file and load its contents into a PostgreSQL table.

    Args:
        engine: SQLAlchemy Engine instance.
        csv_filename: Relative or absolute path to the CSV file.
        table_name: Destination table name (e.g., 'raw.orders').

    Returns:
        The number of rows loaded.

    Raises:
        FileNotFoundError: If the CSV file does not exist.
    """
    data_dir = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
    filepath = os.path.join(data_dir, csv_filename)

    if not os.path.exists(filepath):
        raise FileNotFoundError(f"CSV file not found: {filepath}. Run generate_fake_data.py first.")

    logger.info("Loading %s → %s ...", filepath, table_name)

    # WHY: Read CSV in chunks to avoid loading 100k+ rows into memory at once.
    chunk_size = 10_000
    total_rows = 0

    for chunk in pd.read_csv(filepath, dtype=DTYPE_MAP, chunksize=chunk_size):
        chunk.to_sql(
            table_name.split(".")[1],  # WHY: to_sql needs just the table name.
            engine,
            schema="raw",
            if_exists="append",
            index=False,
            method="multi",  # WHY: multi-row insert is faster than single-row.
        )
        total_rows += len(chunk)

    logger.info("Loaded %d rows into %s", total_rows, table_name)
    return total_rows


def main() -> None:
    """Main entry point: connect to PostgreSQL and load all CSV files."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    start_time = datetime.now()

    try:
        engine = get_engine()
        ensure_raw_schema(engine)

        total_rows = 0
        for csv_file, table_name in CSV_TABLE_MAP:
            truncate_table(engine, table_name)
            rows = load_csv_to_table(engine, csv_file, table_name)
            total_rows += rows

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(
            "Data loading complete! Loaded %d total rows in %.2f seconds.",
            total_rows,
            elapsed,
        )

    except Exception as exc:
        logger.error("Data loading failed: %s", exc, exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
